version: '3.9'

services:
  eventio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      #- "8081"
    volumes:
      - ${APPDATA}/tmp/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/tmp/ASP.NET/Https:/home/app/.aspnet/https:ro